language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g gulp
 - npm install hexo-cli --save
 - npm install hexo-renderer-jade hexo-renderer-stylus hexo-wordcount --save


script:
  # - npm audit fix
  - hexo clean && hexo g
  - cd ./public
  - mv index.html index2.html # rename index.html
  - cp ./custom/via.html ./index.html # use via.html
  - git init
  - git config user.name "symant233"
  - git config user.email "symant233@gmail.com"
  - git add .
  - git commit -m "Travis-CI auto build."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master


# after_script:
#   - cd ../
#   - chmod +x ./bin/autoissue
#   - ./bin/autoissue
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
  global:
    - GH_REF: github.com/symant233/symant233.github.io.git
